name: C++ CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilar
        run: g++ main.cpp -o programa
      - name: Ejecutar
        run: ./programa
  